services:
  - type: web
    name: voiceverse-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: cd server && npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_EXPIRES_IN
        value: 7d
    autoDeploy: false

databases:
  - name: voiceverse-db
    databaseName: voiceverse
    user: voiceverse_user
    plan: starter